### PR TITLE
Update a step on the customisation page to make more sense

### PR DESCRIPTION
**Pull request by mattsoftware**
My previous pull request inserted a step on the customisation page, but after re-reading the page the step immediately after the new step no longer makes sense. This is a small re-write of the step to clear that up.

### CODE REVIEW

**Comment by franklin-lobb** [comment]
included relevant changes in a different update.  Thanks for submitting this PR!

**Comment by mattsoftware** [comment]
Hi. I think you may have missed the point of this pull request. I wrote the bit of text that is on instructions/5-customization.md but after going through the instructions again this bit of text does not make sense. the words "Once you have made the updates listed on this page" does not make sense as there are no updates on this page to make. This pull request changes the wording to "You can now click Distribution....." which makes more sense when going through the tutorial.

I would like you to reconsider this pull request again as I feel it makes that step more easy to understand. However if you feel the current wording is acceptable that is okay too :)

**Comment by franklin-lobb** [comment]
I see where 'updates on this page' could be confusing.  In step 4, I interpreted that to refer to the updates listed on the instruction page (e.g. new sentences, new language).  Do you think that requires clarification?

As for the change in Step 5, I updated the wording as part of other changes, so this specific PR became redundant.  Here's the as it stands now: https://github.com/alexa/skill-sample-nodejs-fact/blob/master/instructions/5-customization.md

**Comment by mattsoftware** [comment]
Ahh, fair enough. I interpreted "on this page" as in the page that I am currently following the instructions for... not the instructions themselves. It makes sense given that context, so leaving it as is is probably fine. Thanks for taking a closer look!

**Pull request closed without merging**
