### PR TITLE
Adds pt-BR to skill.json

### PR DESCRIPTION
**Pull request by s4p0**
*Issue #, if available:*

*Description of changes:*
Adds pt-BR to skill.json so it is enabled by default, like others.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by franklin-lobb** [comment]
just a quick update - I've been investigating this, but still trying to connect with a native speaker to provide a language review.

**Comment by s4p0** [comment]
Great!

BTW @franklin-lobb I'm a native :smile:

**Comment by franklin-lobb** [comment]
I figured, and I don't have any concerns - it's just protocol to have it reviewed by an Amazonian before merging.

**Comment by franklin-lobb** [comment]
Made minor changes based on feedback.  Thanks!

**Pull request merged**
