### PR TITLE
escaping underscores so they show in the docs

### PR DESCRIPTION
**Pull request by cyanliu-zzz**

### CODE REVIEW

**Comment by akersh-s** [comment]
@cyanliu From what I can see, plain text underscores are showing in the docs.

**Comment by akersh-s** [comment]
Closing Pull-Request.

**Comment by cyanliu-zzz** [comment]
Underscores are not showing on the [website](https://developer.amazon.com/alexa-skills-kit/tutorials/fact-skill-2), and are italicizing text instead.
image

**Comment by akersh-s** [comment]
@cyanliu gotcha, thanks! we'll get that fixed

**Pull request closed without merging**
